default: &default
  basecampbot_url: https://3.basecamp.com/3648568/integrations/jSQBpBexDzgJ6sTUSEnT9foQ/buckets/2496221/chats/362174890/lines
  snstopic_arn: arn:aws:sns:us-west-2:482116491549:test_t

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default