# Add this file to .gitignore right now !!!
default: &default
  basecampbot_url: https://3.basecamp.com/3700178/integrations/3gtJyBKVQHvrQN2h7FitRJSK/buckets/3097353/chats/437772399/lines
<<<<<<< HEAD
  snstopic_arn: arn:aws:sns:eu-central-1:798348585423:basecamp-bot
=======
  snstopic_arn: arn:aws:sns:us-west-2:230306836787:magick_kick
  # Path to the .json file that contain contains 'aws_access_key' and 'aws_secret_key'
  aws_secret_file: /home/klim/secrets.json
  # Giphy API url + public API key
  giphy_url: http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC
>>>>>>> bugsnag

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default