default: &default
  basecampbot_url: https://3.basecamp.com/3601306/integrations/6Mc7Rhug2NkpDY53Qu2x7TGn/buckets/1925463/chats/294329172/lines
  snstopic_arn: arn:aws:sns:eu-central-1:798348585423:basecamp-bot

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default