
# Add this file to .gitignore right now !!!
default: &default
  basecampbot_url: https://3.basecamp.com/3999996/integrations/8gtJyBKVQHvrQN2h4FitRJSK/buckets/3797353/chats/434442399/lines
  snstopic_arn: arn:aws:sns:us-west-5:670306886787:magick_kick
  # Path to the .yml file that contains 'aws_access_key' and 'aws_secret_key'
  aws_secret_file: /home/user/secrets.yml
  # Giphy API url + public API key
  giphy_api_key: "dc6zaTOxFJmzC"

development:
  <<: *default

test:
  <<: *default

production:
  basecampbot_url: <%= ENV["BASECAMPBOT_URL"] %>
giphy_api_key: <%= ENV["GIPHY_API_KEY"] %>
