default: &default
  basecampbot_url: https://3.basecamp.com/3700178/integrations/3gtJyBKVQHvrQN2h7FitRJSK/buckets/3097353/chats/437772399/lines
  snstopic_arn: arn:aws:sns:eu-central-1:798348585423:basecamp-bot

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default