default: &default
  basecampbot_url: https://3.basecamp.com/3700178/integrations/3gtJyBKVQHvrQN2h7FitRJSK/buckets/3097353/chats/437772399/lines
  snstopic_arn: arn:aws:sns:us-west-2:230306836787:magick_kick

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default